version: '3.8'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  celery-worker:
    build: .
    command: celery -A app.core.celery_app worker

  celery-beat:
    build: .
    command: celery -A app.core.celery_app beat

  flower:
    build: .
    command: celery -A app.core.celery_app flower